name: kobo

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      KOBOTOOLBOX_USERNAME: ${{ secrets.KOBOTOOLBOX_USERNAME }}
      KOBOTOOLBOX_PASSWORD: ${{ secrets.KOBOTOOLBOX_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_cran(c("shiny", "tidyverse", "httr2"))'
          Rscript -e 'remotes::install_github("mrdwab/KoboconnectR")'

      - name: Run Shiny App
        run: |
          Rscript app.R
